services:
  api:
    build:
      context: ./api
    container_name: api
    volumes:
      - ./api:/usr/app
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8081:8080'
    depends_on:
      - db